### ISSUE TITLE
Instructions unclear for how to join channel

### ISSUE THREAD

**Issue by pekasus** [feliskio/discord-live-translator#22]
I'm trying to set up the bot on one of my servers, and I'm following the readme instructions. It says to type `!translation join` into the voice channel, but there is nowhere to input bot commands in the voice channel. Is there another way to do this? Also, I would like to have different language streams available for the most common languages. Could I create additional channels for each language and connect it to the call channel?

**Comment by feliskio** [comment]
Hi, first of all, sorry for the late response.
The readme file seems to be very outdated so here is the basic rundown:
Instead of using commands prefixed by !translation you now use the slash commands provided by the bot to your server. You can execute these by going into any text channel (starting with #) and typing a /. This will show you multiple all the available commands and their purpose along side auto-complete instructions.
Due to a restriction from Discord a bot can only be in one channel per server at a time. To lift this restriction I'd have to create a second bot that you can invite to your server. But that's something for another time. Right now the bot is intended to be commanded by your users. Language settings are always set by the user and only for themselves. This means that one user could for example be talking French while the other one is talking German and have their input translated into the other person's language.
Hope this was helpful.
