### ISSUE TITLE
Bot does not recognize me inside voice channel

### ISSUE THREAD

**Issue by esppc** [feliskio/discord-live-translator#5]
Pretty much self explanatory. Even when I'm inside the voice channel, the bot will say that I'm not

**Comment by feliskio** [comment]
Have you tried leaving the voice channel and rejoining it while making sure that the bot is running?
Otherwise are there any error messages in the console?

Apart from that please keep in mind that this is a hackathon project that last recieved a feature update in 2019 meaning that it's possible that APIs that it relies on have changed. I might look into modifying it to use free tools for translating in order to make it finacially viable to provide a hosted bot,

**Comment by feliskio** [comment]
no response
